#ifndef KRN_DOS_H
#define KRN_DOS_H

/* basic types */
#include <krn/krntype.h>

/* definitions */
#include <krn/dosint.h>
#include <krn/dosreq.h>

/* forward declarations */
#include <krn/dosfwd.h>

/* actual declarations */
#include <krn/dosdhd.h>
#include <krn/dosdpb.h>
#include <krn/dosivr.h>
#include <krn/dosmcb.h>
#include <krn/dospsp.h>
#include <krn/dossda.h>

#endif
